version: "2"

services:
  web:
    image: hugofooy/vis-a-vis:v0.4
    build: .
    command: nodemon --debug=5858
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8082:8080"
      - "5858:5858"
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    links:
      - mongo
  